### ISSUE TITLE
[Qt] Stormnode Tab Text Difficult To Read.

### ISSUE THREAD

**Issue by AmirAbrams** [SilkNetwork/DarkSilk-Core#15]
### Describe the issue
In the Qt wallet's stormnode tab, the text is white on a grey background making the text difficult to read.
### Steps to reproduce
1. Run DarkSIlk Qt Wallet
2. Select Stormnodes tab
3. Text Under My Stormnodes is difficult to read.
### Expected behavior (tell us what should happen)
Better contrast so the text is readable.
### Screenshots
![My Stormnode Tab](http://i.imgur.com/hw3euSZ.png) 
![All Stormnode Tab](http://i.imgur.com/lJv82O9.png) 
### What platform are you using (Linux, Windows, Mac)
Linux 64-bit (Ubuntu 16.04)

**Comment by spencerlievens** [comment]
<img width="961" alt="screen shot 2016-11-24 at 21 47 32" src="https://cloud.githubusercontent.com/assets/9684063/20610318/a79429a2-b28f-11e6-9431-5b263c2d3ccd.png">

Missed as it shows correctly on OSX

**Comment by SCDeveloper** [comment]
Fixed
