### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by spencerlievens** [SilkNetwork/DarkSilk-Core#22]
### Describe the issue
Fix this styling issue.

### Screenshots
<img width="124" alt="screen shot 2016-11-26 at 19 34 36" src="https://cloud.githubusercontent.com/assets/9684063/20642760/7a4aae2c-b40f-11e6-82c2-52938042d418.png">

### What platform are you using (Linux, Windows, Mac)
OSX El Capitan 10.11.6

**Comment by GregoryBetz** [comment]
What is the issue? I don't see anything wrong.
